version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-video-catalog-service
    image: devtiagoliveira/api-video-catalog-service
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - backend-network
  
  nginx:
    image: nginx:latest
    container_name: nginx-api-video-catalog
    ports:
      - 8888:80
      - 445:443
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge